version: '3'
services:
  jenkins-ci:
    image: jenkins
    container_name: ci
    ports:
      - "8088:8080"
    networks:
      main:
        aliases:
          - jenkins-ci
  mysql:
    image: mysql:5.7
    container_name: dmall_db
    ports:
      - 3306:3306
    environment:
      - LANG=C.UTF-8
      - TERM=dumb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dmall_db
      - MYSQL_PASSWORD=12345678
      - MYSQL_USER=dmalldb
    networks:
      main:
        aliases:
          - mysql
networks:
  main:



