spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dmalldb?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8083